
#-----------------------------------------------------------------------

APP       := HttpApp
TARGET    := HttpServer
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= 

INCLUDE   += #-I/home/tarsproto/HttpApp/TarsInfoServer/
LIB       += 

#-----------------------------------------------------------------------

include /home/tarsproto/HttpApp/TarsInfoServer/TarsInfoServer.mk
include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
